### ISSUE TITLE
Error provisioning CentOS 8 Salt Minion on VirtualBox

### ISSUE THREAD

**Issue by mattboston** [hashicorp/vagrant#11457]
### Vagrant version
Vagrant 2.2.7

### Host operating system
Windows 10 Pro with VirtualBox 6.1.4 r136177

### Guest operating system
CentOS 8 on VirtualBox with Salt

### Vagrantfile

```ruby
VAGRANTFILE_API_VERSION = "2"

os = "centos/8"
box_version = "1905.01"

subnet = '192.168.50.'
master_ip = '10'
minions8 = {
        'minion4' => '14',
        'minion5' => '15',
        'minion6' => '16',
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
  end

  minions.each do |minion, ip|
    config.vm.define "#{minion}" do |minion_config|
      minion_config.vm.box = "#{os}"
      #minion_config.vm.box_version = "#{box_version}"
      #minion_config.vm.box_version = "0"
      minion_config.vm.box_url = "http://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.1.1911-20200113.3.x86_64.vagrant-virtualbox.box"
      minion_config.vm.host_name = "#{minion}.local"
      minion_config.vm.network "private_network", ip: "#{subnet}#{ip}"
      minion_config.vm.network "forwarded_port", guest: 22, host: "22#{ip}", id: "ssh"
      minion_config.vm.provision "shell", inline: "ifup eth1" # centos/7
      minion_config.vm.provision "shell", inline: "mkdir -p /etc/salt/master.d /etc/salt/minion.d; chmod -R a+rw /etc/salt"
      minion_config.vm.provision "file", source: "saltstack/etc/miniond.conf", destination: "/etc/salt/minion.d/miniond.conf"

      minion_config.vm.provision :salt do |salt|
        salt.minion_key = "saltstack/keys/#{minion}.pem"
        salt.minion_pub = "saltstack/keys/#{minion}.pub"
        salt.install_type = "stable"
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp"
        salt.run_highstate = false
        salt.colorize = true
      end
    end
  end

end
```

### Debug output
https://gist.github.com/mattboston/061246662536fa6679577c98217ce5ff

### Expected behavior
I'm getting an error when trying to launch a CentOS 8 vm with Salt.  I have a similar Vagrantfile for CentOS 7 and it works fine.  

### Steps to reproduce

1. vagrant up minion4

**Comment by jbonhag** [comment]
Hi @mattboston,

Thanks for opening an issue with Vagrant! It looks like the `bootstrap-salt.sh` script needs Python 3 packages for CentOS 8. Adding `-x python3` to the Salt `bootstrap_options` in your Vagrantfile should fix the error. For example:

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.provision :salt do |salt|
    salt.install_type = "stable"
    salt.bootstrap_options ="-x python3"
  end
end
```

I'm going to go ahead and close this issue, but you may be interested in following along with https://github.com/saltstack/salt-bootstrap/issues/1418.

Cheers and have a great day! 😄

**Comment by mattboston** [comment]
Still getting errors.  Besides the bootstrap_options, I've also tried adding the following but it didn't work either.  Errors in gist

```
        salt.install_type = "stable"
        salt.bootstrap_options = "-x python3"
        salt.python_version = "3"
```

https://gist.github.com/mattboston/6601328e48c9b014ef28af1f37b058a2

**Comment by jbonhag** [comment]
Hi @mattboston,

Sorry for the confusion, in this case you should change the `salt.bootstrap_options` setting inside the existing block:

```
minion_config.vm.provision :salt do |salt|
  salt.minion_key = "saltstack/keys/#{minion}.pem"
  salt.minion_pub = "saltstack/keys/#{minion}.pub"
  salt.install_type = "stable"
  salt.verbose = true
  salt.colorize = true
  salt.bootstrap_options = "-P -c /tmp -x python3"
  salt.run_highstate = false
  salt.colorize = true
end
```

Would you mind giving that a try and let us know if that fixes the issue? Thanks!
