### ISSUE TITLE
long paths in the vagrant ubuntu disk on win7 causes problems with npm, etc.

### ISSUE THREAD

**Issue by Pomax** [hashicorp/vagrant#1953]
From https://github.com/isaacs/npm/issues/3670, if I run Vagrant on windows 7, the host max path length is 260 characters at the utter most without special instructions/commands, so when running something that has to make deep directories, like checking out a large software project or doing an `npm install`, causes "protocol errors".

For `npm` in particular this is a problem; on native windows `npm` can make use of UNC paths to get around the path limit, and it works brilliant, but inside a vagrant VM the "protocol error" means projects can't be instantiated, and consequently not worked with, effectively negating the benefit that vagrant offers.

I don't know if this is something that can be fixed in Vagrant itself (maybe?) or whether it's a virtualbox issue (I have no other virtualisation software to test that with, unfortunately), but if this can be fixed, that would be amazingly useful for software project virtualisation/testing.

**Comment by drmyersii** [comment]
I've spent about 16 hours working on this today (I wish I was exaggerating), and I finally have a solution to the Vagrant/Windows issue at hand. I have been working on a Node.js development environment built on Vagrant, and I have been relentlessly determined to get this working. 

[This is the commit that I implemented it in](https://github.com/renobit/vagrant-node-env/commit/bdf15f2f301e2b1660b839875e34f172ea8be227), but I'll go ahead and post the main snippet of code here:

```ruby
config.vm.provider "virtualbox" do |v|
    v.customize ["sharedfolder", "add", :id, "--name", "www", "--hostpath", (("//?/" + File.dirname(__FILE__) + "/www").gsub("/","\\"))]
end

config.vm.provision :shell, inline: "mkdir /home/vagrant/www"
config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` www /home/vagrant/www", run: "always"
```

In the code above, I am appending ```\\?\``` to the current directory absolute path. This will actually force the Windows API to allow an increase in the MAX_PATH variable (normally capped at 260). Read more about [max path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath). This is happening during the sharedfolder creation which is intentionally handled by VBoxManage and not Vagrant's "synced_folder" method. The last bit is pretty self-explanatory; we create the new shared folder and then make sure it's mounted each time the machine is accessed or touched since Vagrant likes to reload its mounts/shared folders on each load.

I absolutely hope this helps everyone that was struggling with this like I was!

**Comment by cristiantincu** [comment]
@drmyersii Thanks so much for posting this. Saved my day! :+1:

**Comment by thebeline** [comment]
@drmyersii - Being new to Vagrant, how would I execute your fix only when executing using VirtualBox?

I understand that to dissable a Vagrant "synced_folder" I would `config.vm.synced_folder "./", "/var/www/#{$project}", disabled: true`, so I imagine a full solution would look like:

```
# If VirtualBox, would this look like:
# config.vm.provider "virtualbox" do |v| its self?
  # Dissable the old solder
  config.vm.synced_folder "./", "/var/www/#{$project}", disabled: true
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["sharedfolder", "add", :id, "--name", "project", "--hostpath", (("//?/" + File.dirname(__FILE__) ).gsub("/","\\"))]
  end
  
  config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` project /var/www/#{$project}", run: "always"

# End if VirtualBox, again, just:
# end
```

What would the conditional look like?  Or would I wrap it all in `config.vm.provider "virtualbox" do |v|`?

Sorry if this is really basic.

**Comment by drmyersii** [comment]
Hello, @thebeline! 

You probably want to check out ```override``` in the vagrant documentation. This allows you to override non-provider specific configuration options. Good luck!

http://docs.vagrantup.com/v2/providers/configuration.html

**Comment by thebeline** [comment]
Thanks.

**Comment by thebeline** [comment]
@drmyersii - This does not seem to be working, specifically the `shell` execution.  Can you have [a look](http://stackoverflow.com/questions/29833169/vagrant-provider-override-shell-not-executing)? Thanks.

**Comment by ryanmc2033** [comment]
@drmyersii - I'm having a hard time getting this to work

```
  # settings for VirtualBox provider
  config.vm.provider "virtualbox" do |v, override|
      override.vm.synced_folder "./", "/vagrant", disabled: true

      v.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", (("//?/" + File.dirname(__FILE__)).gsub("/","\\"))]

      override.vm.provision :shell, inline: "mkdir /vagrant"
      override.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant", run: "always"
  end
```

When I open virtualbox and look at the shared folders it looks correct, but the share is not working (my shared dir on the guest is empty)

Does anything look wrong in my setup?

**Comment by Pomax** [comment]
## This got fixed in https://github.com/mitchellh/vagrant/pull/5495

As a note to all, a patch for this behaviour was been merged in, so if you found this issue looking for a way to enable long pathname support: the next version of Vagrant should no longer suffer from this problem. Until then, you should be able to apply the same fix to your vagrant files.

**Comment by chernetsov0** [comment]
@Pomax thanks for fixing this, mate! Appreciate it.

**Comment by Pomax** [comment]
credit goes to @jfbibeau and everyone who helped review and land

**Comment by ryanmc2033** [comment]
Any idea on when the next version of Vagrant is going to be available? Wondering if it is worth patching out my whole team or wait for the update?

**Comment by Pomax** [comment]
patch first, wait second. Worst case the update does exactly the same as your patch, and in the mean time you have a working Vagrant.

**Comment by drmyersii** [comment]
I second @Pomax. It's honestly not much work (as you can see from my comment above), and it would be just as easy to remove once you update.

**Comment by ryanmc2033** [comment]
@drmyersii - As you could see from my previous message I could not get your fix to work. However, after I applied the official fix from #5495 everything works great.

**Comment by drmyersii** [comment]
@ryanmc2033 - Oh! Sorry about that! I didn't even see that you were having issues with my solution. I will take a look at your use case sometime today to see if it's possibly just a mix up in your configuration. I definitely recommend using the official patch if you can though. My solution was just a way to get it working without having to re-compile the source.

**Comment by ryanmc2033** [comment]
@drmyersii - maybe I did something different, but I didn't have to recompile the source. I just found the two files in my install directory, applied the changes in the commit. Then did a destroy and up in vagrant and it worked. Or at least it appears to be working, at least the problems I was having have gone away, but I will have to triple check to make sure I am not imagining things.

**Comment by Jakobud** [comment]
Did this definitely get fixed in 1.7.4? I experienced a similar issue tonight installing some `npm` modules. It threw all sorts of errors when installing in the shared directory, but outside the shared directory (completely within the guest filesystem) it installed just fine with no errors.

**Comment by jfbibeau** [comment]
It got fixed in 1.7.3, but reverted in 1.7.4 as it was causing issues with some versions of VirtualBox. Check out #5933 I believe.

**Comment by Jakobud** [comment]
Oh dang no wonder. I thought this was fixed. Okay so any clue when this is going to make it back into a release?

**Comment by Pomax** [comment]
that is unfortunate. Leaving it broken would have forced the virtualbox team to actually get off their ass and fix something for a change =(

**Comment by Jakobud** [comment]
Yeah bummer. I guess it's back to the good old manually-mounted synced folder workaround:

https://gist.github.com/Jakobud/0768ff6b6051e79eef60

**Comment by Pomax** [comment]
it would have been more sensible to make it a feature flag, so windows users could have used `vagrant up --unc` or something, thus solving the problem for everyone.

**Comment by msimkunas** [comment]
@Jakobud Does this solution work with samba shares on Windows? I'd like to be using something that doesn't slow down performance to a crawl.

**Comment by Jakobud** [comment]
Samba shares..... So what do you mean, you running a Linux guest with a samba share that your Windows host is connecting to?

**Comment by msimkunas** [comment]
I'm running a Linux guest on a Windows host and I wish to improve filesystem performance. Isn't samba the only way for Windows hosts?

-----Pradinis laiškas-----
Nuo: "Jake Wilson" <notifications@github.com>
Išsiųsta: ‎2015-‎08-‎18 07:41
Kam: "mitchellh/vagrant" <vagrant@noreply.github.com>
Kopija: "Mantas Šimkūnas" <mantas.simkunas@gmail.com>
Tema: Re: [vagrant] long paths in the vagrant ubuntu disk on win7 causesproblems with npm, etc. (#1953)

Samba shares..... So what do you mean, you running a Linux guest with a samba share that your Windows host is connecting to?

**Comment by Jakobud** [comment]
No no, you need to use Vagrant's sync'ed folders:

http://docs.vagrantup.com/v2/synced-folders/basic_usage.html

You end up with folders on your host that are automatically and instantly synced with folders on the guest system.

**Comment by msimkunas** [comment]
@Jakobud Actually, I was referring to this: http://docs.vagrantup.com/v2/synced-folders/smb.html

**Comment by Jakobud** [comment]
Oh okay. Why not use regular synced folders? Seems like smb would be only useful if you had multiple physical computers you wanted to connect to a single guest environment. If you are just using one Windows host and one guest, normal synced folders I would think would be great. There is obviously the above mentioned 260-character bug issue, but the gist I posted gets around the problem.

**Comment by msimkunas** [comment]
@Jakobud A shared folder without NFS/SMB is very slow. ag/grep/etc performance is almost unbearable while fuzzy searching a bigger project in vim. I wanted to go for a more performant solution, but I simply gave up on this, because Windows is just so difficult to work with in this regard.

The only way I can work without hassle is by running my projects on a folder inside the guest machine. I'm using a Linux VM with a window manager, chromium, firefox and all other GUI tools that help me forget about the Windows host completely. I wish there was a simple way to alleviate this problem though.

**Comment by msimkunas** [comment]
@Jakobud I could probably use rsync, but I couldn't manage to get it to work properly (could be just me though...). Either way, I just don't like the idea of duplicating files on my machine.

**Comment by Jakobud** [comment]
Hmmm, my synced folders sync instantly from what I can see. There is no lag.

**Comment by vmadman** [comment]
This is killing me... I was on Vagrant 1.7.1 and I've been having the problem for what seems over a year.  I get all excited with all of the "fixed" talk above so I upgrade to Vagrant 1.7.4 .. only to realize that it was fixed then removed.  The Vagrantfile workaround above looks complicated and I could not immediately see how I could apply it to my situation... idk what Virtualbox is doing on their end.

Can we at least get the fix put back into Vagrant with some sort of special flag, as @Pomax suggested?  (`vagrant up --unc`)

I know its not perfect, but considering the alternatives its marvelous and magical by contrast.. at least its a viable workaround!  Please?

**Comment by sergeikretov** [comment]
Still having the same issue on Win 8.1 pro with VirtualBox 4.3.30 and vagrant 1.7.2. Is it going to be fixed? Cause I tried also VirtualBox 5.0.4 and vagrant 1.7.4, but same stuff and no luck.

**Comment by Pomax** [comment]
that's becuase it only works with virtualbox <5 and vagrant 1.7.3 -- the fix was landed in 1.7.3 and then broke incredibly hard with virtualbox 5, so got rolled back.

**Comment by vmadman** [comment]
Yeah, I don't think they care much about this -- its been going on for a very long time. However, I reverted to 1.7.3 and it has been working so far.

**Comment by sergeikretov** [comment]
VirtualBox 4.3.30 + Vagrant 1.7.3 combo worked fine to me, thank you.

**Comment by Pomax** [comment]
I honestly couldn't care less about virtualbox 5, really. I just want this patch back in under a runtime flag so it can be used as necessary. And then Virtualbox could sort out their own mess and actually maybe fix something for a change.

**Comment by dhampik** [comment]
@mitchellh This issue should probably be reopened, since fix in version 1.7.3 is reverted in 1.7.4 and basically the only working version is Virtualbox 4.3 + Vagrant 1.7.3.

I heard some people are unable to install Virtualbox 4.3 on Windows 10, so they **cannot use Vagrant at all** for their needs and that issue is a **blocker**. Maybe we should cooperate with Virtualbox guys to solve that?

**Comment by Perni1984** [comment]
- the UNC path fix is back in the 1.8 Version of Vagrant which should be available soon, in the meantime one can add the PR by Hand (#6493)
- a suitable way to use npm inside an ubuntu/vivid64 box on Windows 10, Vagrant 1.7.4 and VirtualBox 5.0.10 is to use smb for the synced Folders, force smb protocol Version 3.02 and add emulated symlink compatability through mfsymlinks. After this, my Setup with npm works absolutely fast and flawlessly:

```
config.vm.synced_folder "../.", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
```

**important: the guest OS must have a Linux kernel Version > 3.18, otherwise mfsymlinks is not working!**

**Comment by Jakobud** [comment]
FYI with Node version 5.x, npm is different than it used to be. Now all dependencies are installed in a flat folder structure instead of having endlessly nested dependency folders in node_modules. So it makes it a lot easier on Vagrant installs in Windows even without the UNC fix.

**Comment by Perni1984** [comment]
@Jakobud: while that's true, I still experienced some weird problems in Windows for some of my node.js apps (especially my gulpfile related dependencies of certain Projects) without mfsymlinks and the UNC fix.

**Comment by dantheman213** [comment]
Hey guys, I created a script to fix this issue. My solution was to execute the project in a part of the VM that wasn't being shared with Windows. The script can be run over and over again to run a project. It copies the base project to a temporary execution directory. If you're running it 2nd time + it checks for file differences and will run npm install if your "package.json" file has changed. Lastly it runs npm install inside the execution directory and voila! Workaround complete. :)

Check it out here guys:
https://gist.github.com/dantheman213/7a505004d26c480e8274

**Comment by fchastanet** [comment]
Thanks dantheman213, very good idea
