### ISSUE TITLE
Rsync on Windows using cwRsync fails with No such file or directory (2)

### ISSUE THREAD

**Issue by balajisivaraman** [hashicorp/vagrant#3230]
Hi,

I am trying to set up an Rsync share on a Windows 8 machine with a Ubuntu 12.04 LTS Guest VM, and it fails with the following error.

```
Balaji@GANESHA-PC /c/Coding/Ruby/discourse (master)
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'discourse-0.9.7'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: discourse_default_1394892063920_77253
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3000 => 4000 (adapter 1)
    default: 1080 => 4080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Error: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /c/Coding/Ruby/discourse/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Coding/Ruby/discourse/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z -e ssh -p 2222 -o StrictHostKeyChecking=no -i 'C:/Users/Balaji/.vagrant.d/insecure_private_key' --exclude .vagrant/ /c/Coding/Ruby/discourse/ vagrant@127.0.0.1:/vagrant
Error: rsync: change_dir "/c/Coding/Ruby/discourse" failed: No such file or directory (2)
FATAL I/O ERROR: dying to avoid a --delete-during issue with a pre-3.0.7 receiver.
rsync error: requested action not supported (code 4) at flist.c(1882) [sender=3.1.0]
```

I am using cwRsync version 3.1.0 downloaded from the following location: https://www.itefix.no/download/cwRsync_5.2.2_Free.zip

I am running this in a Git Bash window with Administrative Privileges. My user is also the owner of the directory being shared, so I doubt whether it could be an issue where I don't have enough privileges.

The Rsync version in the Guest is 3.0.9. At first, I thought that was the issue. But even if I manually install 3.1.0 from source, I am getting the same error.

Any advice? Thanks in advance.

**Comment by Ortix92** [comment]
+1

**Comment by jakul** [comment]
@osroot25 +1 thanks for the workaround!

**Comment by fresheneesz** [comment]
+1

**Comment by sveri** [comment]
+1

**Comment by mmodler** [comment]
+1

**Comment by fletchowns** [comment]
+1

The [vagrantfile workaround](https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180) worked for me in msysgit but I also have cygwin installed, which is where it's getting rsync from:

```
Welcome to Git (version 1.9.4-preview20140611)

$ which rsync
/c/cygwin64/bin/rsync
```

**Comment by iamsteveholmes** [comment]
None of the Vagrant workarounds seem to work for me.  I'm on 32 bit cygwin and windows 7.

**Comment by NathanielMichael** [comment]
+1 Editing the library worked for me.

The machine I'm testing with has Cygwin installed but last on the PATH (just for rsync). Mainly using Git Bash + Cmder, so it's not detected as Cygwin properly.

Is there a way to test the rsync binary directly to determine if it's a Cygwin distributed binary? That may be the best option to support as many configurations as possible.

**Comment by chrisg123** [comment]
@osroot25 's solution worked for me as well
    Vagrant.configure(2) do |config|
      ... your own config...etc.
      ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
    end

**Comment by jamesvl** [comment]
For some reason it doesn't work for me - editing the Vagrantfile to modify `ENV` never made it to the helper or plugin scripts in Vagrant, both in `vagrant up` or `vagrant rsync`.

I traced through the code; even though `cygwin_path()` is getting called in `platform.rb` (since my platform comes back as "mingw32"), it uses the alternate bash script to detect the path, which leaves off the necessary `/cygdrive` prefix (~ line 74).

I ended up adding an additional check in `cygwin?` using an `ENV` variable that *was* set properly: `TERM`.

Edit: `embedded\gems\gems\vagrant-1.7.3\lib\vagrant\util\platform.rb` on line 16 (Vagrant 1.7.3):

```ruby
return true if ENV["TERM"] &&
  ENV["TERM"].downcase.include?("cygwin")
```

After this, the vagrant commands `up`, `rsync`, and `rsync-auto` all work as expected for me.

**Comment by AnthonyMastrean** [comment]
@jamesvl Only the MSYS or Git Bash terminal reports its `TERM` as `cygwin`. What about native Windows consoles, where Vagrant should also work, like `cmd.exe` and PowerShell?

**Comment by lucassch** [comment]
> Works for me:
> 
> Install Cygwin
> Instal rsync package: apt-cyg install rsync
> Changing line 43 in C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.X\plugins\synced_folders\rsync\helper.rb to hostpath = "/cygdrive" + Vagrant::Util::Platform.cygwin_path(hostpath)
> Thanks @Venorcis.

Works for me too! Thanks @Venorcis @brunowego

**Comment by AnthonyMastrean** [comment]
We still need a solution that works without cygwin on Windows. i'm putting together some info now. Will post later.

**Comment by GBuella** [comment]
Hi, just a note:
An easier way to set VAGRANT_DETECTED_OS is to set it as an environment variable in cygwin, this worked for me:

VAGRANT_DETECTED_OS=cygwin vagrant up

or if needed, place it in your bash startup file .profile, .bashrc in your cygwin home , whatever.
This way, things still work with cmd.exe, as the you would only set the environment variable in cygwin.

**Comment by binarycrafts** [comment]
I have tried cwRsync, MinGW and cygwin on Windows 7.1 and the only way I got rsync working is with cygwin by using the cygwin shell and setting
```
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
```
in the Vagrant file.
For me this would go into the Vagrant file because I require each developer to customize these files anyways.

**Comment by JaminShanti** [comment]
@binarycrafts  nice, share your solution with mitchell....

**Comment by AnthonyMastrean** [comment]
@JaminShanti cygwin and the cygwin shell are not a solution that I can use and I suspect that others will have the same restriction. For rsync to be fully supported on Windows, it must be possible in any shell.

**Comment by hotnuts21** [comment]
Im just trying to get my first ever vagrant box up!

Installed the latest versions of Virtualbox, Vagrant, Putty, and then when i got rsync errors I installed Cygwin with rsync.

have tried both the options here, moved the rsync so it comes before git in the global path and still I get the following error when trying to run vagrant up in a cmd. (with ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin" in the vagrant file)

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: gettingStarted-centos7_default_14507149
03141_9313
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest

    default: additions are required for forwarded ports, shared folders, host on
ly
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work prope
rly,
    default: in which case you may ignore this message.
==> default: Installing rsync to the VM...
==> default: Rsyncing folder: /cygdrive/c/Users/paul/Projects/gettingStarted-cen
tos7/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/Users/paul/Projects/gettingStarted-centos7/
Guest path: /home/vagrant/sync
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no
-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHos
tKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Us
ers/paul/Projects/gettingStarted-centos7/.vagrant/machines/default/virtualbox/pr
ivate_key' --exclude .vagrant/ /cygdrive/c/Users/paul/Projects/gettingStarted-ce
ntos7/ vagrant@127.0.0.1:/home/vagrant/sync
Error: rsync: Failed to exec ssh: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.1]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=
3.1.1]

Any ideas greatly appreciated.

**Comment by hotnuts21** [comment]
Fixed my own problem and putting instructions here for anyone else in similar problem. The issue is that SSh is not installed on windows and even though I had installed it via cygwin, it was not set up to run as a service.
Heres a handy guide on getting it running under windows http://www.howtogeek.com/howto/41560/how-to-get-ssh-command-line-access-to-windows-7-using-cygwin/

**Comment by smolinari** [comment]
The suggestion with 

`ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"`

fixed my problem. Thanks @osroot25! :+1: 

Scott

**Comment by PropTim** [comment]
The original problem is still on windows 10. The line edit fixed it:

`hostpath = "/cygwin" + Vagrant::Util::Platform.cygwin_path(hostpath)`

**Comment by smolinari** [comment]
This issue is still in 1.8.1 too. 

Scott

**Comment by terrancesnyder** [comment]
+1 Still doesnt work on 10

**Comment by AgentCormac** [comment]
+1 Vagrant 1.8.1 & Win7

**Comment by hollowimage** [comment]
+1 on win10 w/ embedded git bins into powershell.

**Comment by strarsis** [comment]
+1 Vagrant 1.8.5 on Windows 10

**Comment by hollowimage** [comment]
Updating to lates (1.8.5) fixed the issue for me.

@strarsis if you got 1.8.5 and its not working, maybe the upgrade didnt finish properly?  How does the rsync_helper.rb look for you? Maybe the installation got messed up?

meanwhile, try this: https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180

**Comment by strarsis** [comment]
I am using cygwin rsync now instead of cwRsync and this works fine.

**Comment by craigsagit** [comment]
Thank you @starrychloe

**Comment by chebaby** [comment]
@mdoelker you pointed me in to the right [direction](https://github.com/hashicorp/vagrant/issues/3230#issuecomment-54714840)

thank you
