### ISSUE TITLE
shared folder problem

### ISSUE THREAD

**Issue by till** [hashicorp/vagrant#351]
We've run into weird inconsistency issues with shared folders.

This is the configuration in `Vagrantfile`:

```
config.vm.share_folder("v-data", "/vagrant_data", "~/project")
```

When I edit a file on the share -- either by `vagrant ssh` into the VM and editing directly, or on the host system -- I can see the change done to a file when I `cat foo`, etc.. However, it gets tricky when this file is a static asset served by nginx. So no matter what I do, the state of the file is not refreshed and the content delivered is the same as when I started the VM (`vagrant up`). To refresh the file I have to either rename it permanently, or `vagrant destroy && vagrant up`.

My nginx configuration is pretty generic. The reason why I rule out nginx is, that I ran into someone with the same issue, and he's using a `share_folder` in Vagrant as well.

I found this issue in `0.6.9` and also `0.7.3`.

Supposedly this works better when an NFS export is used. I'm testing this next.

**Comment by AmazingDreams** [comment]
I had the same issue and tried NFS. NFS possibly corrupted my git index. I had an error similar to this: http://stackoverflow.com/questions/4254389/git-corrupt-loose-object

Not sure where it came from exactly as I just booted up to find that error.

**Comment by KrunoKnego** [comment]
Please add the information about Virtualbox send file bug on: http://docs.vagrantup.com/v2/synced-folders/nfs.html.

**Comment by zhangjingjing2020** [comment]
@mitchellh
thanks！

**Comment by lordgiotto** [comment]
Still no solution for this bug? I need to use x-sendfile module in my project and EnableSendfile on is mandatory :|

**Comment by TajPelc** [comment]
If I add "sendfile off;" to my config the consistency issues are solved, but page loads where a lot of static files are served become extremely slow. They go from 1s to 12s. Has anyone else had the same problem?

**Comment by CleanCut** [comment]
sendfile is a feature to speed things up, and it's broken, so it's pretty normal that things slow down (but work correctly) when you turn it off, although it wasn't as extreme a slowdown for me as it was for you.  I found it very interesting that performance increased a ton when I upgraded from boot2docker 1.7 to boot2docker 1.8.  Boot2docker bundles their own version of VirtualBox, so I'm wondering if there was something changed there that affected things.

**Comment by kenorb** [comment]
Related VirtualBox bugs to this issue: [#819][1], [#9069][3], [#12597][2], [#14920][4].

Related posts (with some workarounds):

- [Vagrant/VirtualBox/Apache2 Strange Cache Behaviour](http://stackoverflow.com/q/9479117/55075)
- [No visible cause for “Unexpected token ILLEGAL”](http://stackoverflow.com/q/12719859/55075)
- [Shared folder in VirtualBox for Apache](http://stackoverflow.com/q/6298933/55075)
- [JS and CSS files in vagrant not properly encoded when saved outside of the VM](http://stackoverflow.com/q/12782946/55075)

  [1]: https://www.virtualbox.org/ticket/819
  [2]: https://www.virtualbox.org/ticket/12597
  [3]: https://www.virtualbox.org/ticket/9069
  [4]: https://www.virtualbox.org/ticket/14920

**Comment by gnulnx** [comment]
I know this is closed, but non of these fixed my issue.  Turns out I also had to update gunicorn to not use sendfile.

https://github.com/hashicorp/vagrant/issues/7163

**Comment by criscola** [comment]
This is far from being a solved issue. I'm running a Golang webserver using Vagrant, modified a .css file but the changes are not visible until doing a `vagrant destroy`. If a try to do the same action on a vmware virtual machine, everything is working fine. I went crazy for hours because of this problem... I still have to find a working solution as the only solution I found are related to apache or nginx (which I don't use). The weirdest thing is that if I `cat` my file, I can see them modified, but not if I try to access through the webserver...

**Comment by mhitza** [comment]
According to latest status this should be fixed in VirtualBox 6.0.6, can anyone knows how to easily reproduce the issue confirm the fix?

**Comment by qazd** [comment]
> According to latest status https://www.virtualbox.org/ticket/9069 this should be fixed in VirtualBox 6.0.6, can anyone that knows how to easily reproduce the issue confirm the fix?

It is not fixed for me, VirtualBox 6.0.14 running Ubuntu Xenial on 4.4.0 Kernel

> Golang webserver using Vagrant

The only way is to not use sendfile for shared folders until it's fixed. I don't know Goland, but that https://github.com/wader/disable_sendfile_vbox_linux might be helpful.
