### ISSUE TITLE
Gives: Conflicting dependencies for net-ssh

### ISSUE THREAD

**Issue by hayetech** [hashicorp/vagrant#9983]
### Vagrant version
1.9.4 (Have to run this version to match specifications for cookbook specified version for chef)

### Host operating system
macOS High Sierra (10.13.4)
### Guest operating system
Ubuntu 14.04

### Expected behavior
Should install the plugin `vagrant-librarian-chef` using `vagrant plugin install vagrant-librarian-chef`
### Actual behavior
Gives the following error,
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies net-ssh (~> 4.1.0) and net-ssh (> 0)
  Activated net-ssh-0.5.0
  which does not match conflicting dependency (~> 4.1.0)

  Conflicting dependency chains:
    net-ssh (> 0), 0.5.0 activated

  versus:
    vagrant-share (> 0), 1.1.7 activated, depends on
    vagrant (>= 1.9.2), 1.9.4 activated, depends on
    net-ssh (~> 4.1.0)

  Gems matching net-ssh (~> 4.1.0):
    net-ssh-4.1.0
```
### References
#9388, #8948 
Update: Using their technique of uninstalling and re-installing from the installer package, does not seem to work (installer package is of the same vagrant version of 1.9.4) 

@mitchellh , @chrisroberts, @briancain

**Comment by chrisroberts** [comment]
Hi there,

Please provide a gist with the debug output from running the failed plugin installation. It is not obvious from the provided output where the net-ssh version 5.0 is coming from, and looks as though it was previously installed. Removing all installed plugins and dependencies and trying again may also resolve the problem (using the `plugin expunge` command).

Cheers!

**Comment by hayetech** [comment]
Hey thanks for the timely response, these might help in the further debugging process.
## Debug output
https://gist.github.com/hayetech/428a3d9be11054c42750b27de8b7f437
## Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-trusty-64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.synced_folder "./django", "/django"
   config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.network "forwarded_port", guest: 80, host: 8001
  config.vm.network "forwarded_port", guest: 8000, host: 8888

  config.librarian_chef.cheffile_dir = "../"

  config.vm.provision "chef_solo" do |chef|
    chef.data_bags_path = "../data_bags"
    chef.cookbooks_path = [ "../site-cookbooks",  "../cookbooks"]
    chef.roles_path =  "../roles"
    chef.environments_path = '../environments'
    chef.add_role("django")
    chef.environment = "django"
    chef.json = {}
  end
end
```

## Steps to reproduce
1. `Vagrant up`
1a. (Gives Vagrant: * Unknown configuration section 'librarian_chef'.)
2. `Vagrant plugin install vagrant-librarian-chef`
2a. (Gives the provided gist debug output)


## Currently suggested approach
As suggested of using `plugin expunge` doesn't help in the process, I have tried pretty much all uninstall/reinstall method for instance, going as far as even deleting vagrant folders from 
a) /opt/vagrant
b) /Users/[user-name]/.vagrant.d 
and reinstalling the vagrant again but didn't help.

**Comment by hayetech** [comment]
Still waiting on reply, as the problem still persists. @chrisroberts

**Comment by chrisroberts** [comment]
@hayetech It looks like the constraints aren't being enforced tightly enough when resolving the dependencies. This will likely be fixed by upgrading Vagrant.

**Comment by hayetech** [comment]
Hi,

Upgrading vagrant to 1.9.6 fixes the dependancy issues, but `vagrant up` command still cannot execute the given cookbooks.

## Debug output
As seen in gist report, chef provisioner fails to deploy the cheffile.
https://gist.github.com/hayetech/ec0ea2ddf18cae13dd11215b328c8982

Insight will be highly appreciated.

**Comment by chrisroberts** [comment]
There seems to be an error in one of your recipes. From the gist:

> FATAL: NoMethodError: undefined method `python' for #<Chef::Node::Attribute:0x000000000579e5c8>

Going to close this issue as the original issue has been resolved. Cheers!
